current_lang = "ru"

TEXTS = {
    "ru": {
        "menu_title": "Incremental Coin Game",
        "btn_prestige": "Престиж",
        "btn_play": "Играть",
        "btn_help": "Как играть?",
        "btn_close": "X",
        "ui_upgrades": "Апгрейды",
        "ui_balance": "Баланс",
        "tab_coins": "Монетки",
        "tab_map": "Карта",
        "tab_general": "Общее",
        "grp_bronze": "Бронзовая монетка",
        "grp_silver": "Серебряная монетка",
        "grp_gold": "Золотая монетка",
        "grp_combo": "Комбо",
        "grp_common": "Общее для монеток",
        "grp_wisp": "Летающий висп",
        "grp_zone2": "Зона x2",
        "grp_zone5": "Зона x5",
        "grp_tornado": "Торнадо",
        "grp_meteor": "Метеорит",
        "grp_settings": "Настройки",
        "btn_buy_bronze": "Купить бронзовую",
        "btn_bronze_val": "Цена бронзовой x2",
        "btn_silver_crit": "Шанс крита серебра",
        "btn_silver_crit_size": "Размер крита серебра",
        "btn_silver_val": "Цена серебряной x2",
        "btn_gold_explode": "Золото переворачивает",
        "btn_grab": "Взять золотую на ПКМ",
        "btn_gold_val": "Цена золотой x2",
        "btn_unlock_combo": "Открыть комбо",
        "btn_combo_limit": "Лимит комбо",
        "btn_autoflip": "Авто-переворот",
        "btn_fuse_silver": "Слияние в серебро",
        "btn_fuse_gold": "Слияние в золото",
        "btn_wisp": "Висп",
        "btn_wisp_speed": "Скорость виспа",
        "btn_wisp_size": "Размер виспа",
        "btn_spawn_zone2": "Зона x2",
        "btn_zone2_size": "Размер зоны x2",
        "btn_zone2_mult": "Множитель зоны x2",
        "btn_spawn_zone5": "Зона x5",
        "btn_zone5_size": "Размер зоны x5",
        "btn_zone5_mult": "Множитель зоны x5",
        "btn_spawn_tornado": "Торнадо",
        "btn_tornado_cd": "КД Торнадо",
        "btn_spawn_meteor": "Метеорит",
        "btn_meteor_cd": "КД метеорита",
        # ИСПРАВЛЕНО: Ключи престижа
        "prestige_level_text": "Уровень Престижа: {0} (x{1} Доход)",
        "prestige_need": "Престиж (Нужно > 1B)",
        "prestige_gain": "Престиж (+{0})",
        # ИСПРАВЛЕНО: Ключи звука
        "sound_on": "Звук: Вкл",
        "sound_off": "Звук: Выкл",

        "btn_new_game": "Новая игра",
        "btn_victory": "Победа??",
        "status_max": "Макс.",
        "status_purchased": "Куплено",
        "status_fuse_need": "нужно",
        "status_fuse_silver": "Слияние в серебро",
        "status_fuse_gold": "Слияние в золото",
        "help_goal": "ОСНОВНАЯ ЦЕЛЬ:",
        "help_goal_text": "Накапливайте баланс, покупайте улучшения.",
        "help_gameplay": "ГЕЙМПЛЕЙ:",
        "help_gameplay_text": "Нажмите на монетку, чтобы подбросить её.\nЕсли выпадет Орел, вы получаете деньги.",
        "help_fusion": "СЛИЯНИЕ:",
        "help_fusion_text": "5 Бронзовых -> 1 Серебряная\n3 Серебряных -> 1 Золотая",
        "help_luck": "Удачи!",
        "lang_ru": "RU",
        "lang_en": "EN",
    },
    "en": {
        "menu_title": "Incremental Coin Game",
        "btn_play": "Play",
        "btn_prestige": "Prestige",
        "btn_help": "How to play?",
        "btn_close": "X",
        "ui_upgrades": "Upgrades",
        "ui_balance": "Balance",
        "tab_coins": "Coins",
        "tab_map": "Map",
        "tab_general": "General",
        "grp_bronze": "Bronze Coin",
        "grp_silver": "Silver Coin",
        "grp_gold": "Gold Coin",
        "grp_combo": "Combo",
        "grp_common": "Common",
        "grp_wisp": "Wisp",
        "grp_zone2": "Zone x2",
        "grp_zone5": "Zone x5",
        "grp_tornado": "Tornado",
        "grp_meteor": "Meteor",
        "grp_settings": "Settings",
        "btn_buy_bronze": "Buy Bronze",
        "btn_bronze_val": "Bronze Value x2",
        "btn_silver_crit": "Silver Crit Chance",
        "btn_silver_crit_size": "Silver Crit Size",
        "btn_silver_val": "Silver Value x2",
        "btn_gold_explode": "Gold Flips Others",
        "btn_grab": "Grab Gold (RMB)",
        "btn_gold_val": "Gold Value x2",
        "btn_unlock_combo": "Unlock Combo",
        "btn_combo_limit": "Combo Limit",
        "btn_autoflip": "Auto-Flip",
        "btn_fuse_silver": "Fuse to Silver",
        "prestige_level_text": "Prestige Level: {0} (x{1} Income)",
        "prestige_need": "Prestige (Need > 1B)",
        "prestige_gain": "Prestige (+{0})",
        "sound_on": "Sound: ON",
        "sound_off": "Sound: OFF",
        "btn_fuse_gold": "Fuse to Gold",
        "btn_wisp": "Wisp",
        "btn_wisp_speed": "Wisp Speed",
        "btn_wisp_size": "Wisp Size",
        "btn_spawn_zone2": "Spawn Zone x2",
        "btn_zone2_size": "Zone x2 Size",
        "btn_zone2_mult": "Zone x2 Multiplier",
        "btn_spawn_zone5": "Spawn Zone x5",
        "btn_zone5_size": "Zone x5 Size",
        "btn_zone5_mult": "Zone x5 Multiplier",
        "btn_spawn_tornado": "Tornado",
        "btn_tornado_cd": "Tornado Cooldown",
        "btn_spawn_meteor": "Meteor",
        "btn_meteor_cd": "Meteor Cooldown",
        "btn_new_game": "New Game",
        "btn_victory": "Victory??",
        "status_max": "Max",
        "status_purchased": "Purchased",
        "status_fuse_need": "need",
        "status_fuse_silver": "Fuse to Silver",
        "status_fuse_gold": "Fuse to Gold",
        "help_goal": "MAIN GOAL:",
        "help_goal_text": "Accumulate balance, buy upgrades.",
        "help_gameplay": "GAMEPLAY:",
        "help_gameplay_text": "Click a coin to toss it.\nIf Heads, you get money.",
        "help_fusion": "FUSION:",
        "help_fusion_text": "5 Bronze -> 1 Silver\n3 Silver -> 1 Gold",
        "help_luck": "Good Luck!",
        "lang_ru": "RU",
        "lang_en": "EN",
    }
}


def get_text(key):
    return TEXTS[current_lang].get(key, key)


def toggle_language():
    global current_lang
    current_lang = "en" if current_lang == "ru" else "ru"